### PR TITLE
015 remove dot from guardian file

### PR DESCRIPTION
**Pull request by wout**
This is a fix for #15.

### CODE REVIEW

**Comment by marceloboeira** [comment]
@f @f1reflyyyylmao I don't have strong opinions... I believe it started as `.guardian.yml` because it is part of personal preference rather than the project itself...

**Comment by marceloboeira** [comment]
@wout could u rebase with master?

**Comment by wout** [comment]
@marceloboeira Done!

**Comment by marceloboeira** [comment]
@wout there are still conflicts :/

**Comment by f** [comment]
Can you make it `.guardian.yml` OR `guardian.yml`? People who already use `.guardian.yml` will have problems when they try to update. It should be back-compatible.

Readme file can stay as `guardian.yml`.

**Comment by wout** [comment]
@f Good idea, I'll do that.

@marceloboeira Strange, I'll give it another go.

**Comment by marceloboeira** [comment]
@wout now it is working. Once you make it backwards-compatible I can merge it ;)

**Comment by wout** [comment]
@marceloboeira Voila! :)

**Comment by marceloboeira** [comment]
Perfect!

**Pull request merged**
